version: '3'
services:
  php:
    image: php:7.4-cli
    volumes:
      - ./:/purchase-cigarettes
    tty: true
    stdin_open: true
  composer:
    image: composer:2.0.7
    volumes:
      - ./:/app
    command: install